### ISSUE TITLE
Inline source map issue

### ISSUE THREAD

**Issue by andywillis** [babel/broccoli-babel-transpiler#12]
Hi. Sorry if this is a dumb question, but how do I get the sourcemaps to appear? Currently I have:
```javascript
var appJs = esTranspiler(appTree, {
  sourceMap: 'inline'
});
```
but this doesn't work even though `sourcemap` is the only valid option name I've found. `sourceMap: true` doesn't work either. It's doing everything else fine.

**Comment by Dremora** [comment]
With `sourceMap: 'inline'`, I can see source maps in Firefox but not in Chrome.

**Comment by myfreeweb** [comment]
Use [broccoli-source-map](https://github.com/myfreeweb/broccoli-source-map) to extract inline source maps at the end of the pipeline.

**Comment by stefanpenner** [comment]
i can confirm this works for us right now.
