### ISSUE TITLE
Version 6.1.4 not tagged "latest" on npm

### ISSUE THREAD

**Issue by joliss** [babel/broccoli-babel-transpiler#129]
Perhaps this is intentional, in which case please close this, but I just ran "npm install --save broccoli-babel-transpiler" and ended up being surprised that it installed version 5.7.4, rather than 6.1.4.

```sh
$ npm dist-tag ls broccoli-babel-transpiler
latest: 5.7.4
next: 7.0.0-beta.2
old: 5.5.1
```

**Comment by Turbo87** [comment]
I assume this is related to https://github.com/Turbo87/auto-dist-tag/pull/24, which seems to be missing from the TravisCI config here. I'll fix the disttags manually.

**Comment by Turbo87** [comment]
Resolved by https://github.com/babel/broccoli-babel-transpiler/pull/130
