### ISSUE TITLE
Imports conflict with local variables

### ISSUE THREAD

**Issue by rlivsey** [babel/broccoli-babel-transpiler#14]
I'm using Ember CLI, with ember-cli-babel which in turn uses this addon. This may want to be opened as an issue in babel itself?

I have the following in my app:

```javascript
import {
  updateMeeting
} from 'minutebase/use-cases/meeting';

export function setupAgenda(meeting) {
  return updateMeeting(meeting);
};
```

Which appears to be being transpiled to:

```javascript
define('minutebase/use-cases/agenda', ['exports', 'ember', 'minutebase/use-cases/meeting'], function (exports, Ember, meeting) {
  'use strict';

  exports.setupAgenda = setupAgenda;

  function setupAgenda(meeting) {
    return meeting.updateMeeting(meeting);
  }
});
```

Notice that there's an imported `meeting` and a local `meeting` which tramples on it so `meeting.updateMeeting` is `undefined`.

**Comment by nightire** [comment]
Interesting edge case, I believe this should be solved (hopefully) by Babel itself, as a plugin, broccoli-babel-tanspiler doesn't handle naming mapping, it just follow the way Babel does.

@sebmck what's your opinion on this one?

**Comment by sebmck** [comment]
ember-cli doesn't use Babel for modules. Babel modules are blacklisted and
esperanto is used.

On Wednesday, 4 March 2015, Albert Yu <notifications@github.com> wrote:

> Interesting edge case, I believe this should be solved (hopefully) by
> Babel itself, as a plugin, broccoli-babel-tanspiler doesn't handle naming
> mapping, it just follow the way Babel does.
>
> @sebmck <https://github.com/sebmck> what's your opinion on this one?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/broccoli-babel-transpiler/issues/14#issuecomment-77105623>
> .
>


-- 
Sebastian McKenzie

**Comment by rlivsey** [comment]
@sebmck that makes sense, I was wondering why the output was different to what I saw on the babel repl. 

Probably worth closing this and I'll re-open on ember-cli.

**Comment by rlivsey** [comment]
For anyone following, I think this is due to https://github.com/esperantojs/esperanto/issues/116
