### ISSUE TITLE
Polyfill missing in output due to bad path handling

### ISSUE THREAD

**Issue by Elberet** [babel/broccoli-babel-transpiler#161]
In the lines quoted here, the plugin constructs a path to `@babel/core` in order to fetch the browser polyfill into the broccoli pipeline:

https://github.com/babel/broccoli-babel-transpiler/blob/7c4a3349ff3aaa32690324814e53b0dce1343bfe/index.js#L64-L65

On one of my development systems, this fails because npm installs `@babel/core` into `./node_modules/@babel/core`; as a result, the path returned by `require.resolve()` no longer matches `/\/babel-core\/.*$/` -- and my other development system is a Windows 10 machine, where `require.resolve()` returns a path separated with backslashes.

**Comment by Turbo87** [comment]
that is definitely a bug, thanks for reporting! do you have time to open a PR that fixes the issue?

**Comment by Turbo87** [comment]
I think the right way to do this would be roughly like this:
```js
var babelCorePath = path.dirname(require.resolve('@babel/core/package.json'));
```
in that case we shouldn't need the regex anymore at all

**Comment by Elberet** [comment]
Can do, but I'm not certain on the details. From what I can see, things changed quite a bit.
In the Babel packages I'm using - all from the v7 release - the polyfill is found in `./node_modules/@babel/polyfill/browser.js`; is that the right file to include? Should it be renamed?

**Comment by Elberet** [comment]
After spending some time with the code and its tests, I'm wondering what the desired outcome of adding the `browserPolyfill` flag should actually be:

* just add the polyfill to the output tree?
* place it somewhere where Babel can resolve it while transpiling source scripts?
* all of the above?

Is the option even required for the current version of Babel? It's now all designed around separate packagers that eventually pull the polyfill into a bundle, and Babel will happily transpile scripts that require it even without the browser polyfill script visible at transpile-time.

**Comment by Turbo87** [comment]
to be honest, I don't know the answers to that either. I would suggest to start digging in https://github.com/babel/ember-cli-babel and see if/how that option is used.
