### ISSUE TITLE
upgrade node-workerpool for WorkerThread support

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#164]
https://github.com/josdejong/workerpool/pull/50

- [ ] upgrade workerpool
- [ ] configure it to `auto`
- [ ] ensure we have node 11 test coverage

**Comment by Turbo87** [comment]
I guess it would be best to enable dependabot for this repo, I'm just not sure if we have the necessary permissions to do that on the Babel org

**Comment by stefanpenner** [comment]
@Turbo87 manual for now i guess

**Comment by stefanpenner** [comment]
closing in-favor of https://github.com/babel/broccoli-babel-transpiler/pull/165
