### ISSUE TITLE
Suggest using core-js directly

### ISSUE THREAD

**Issue by charuwts** [babel/broccoli-babel-transpiler#177]
Received this warning when installing ember-cli.

```
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3
```
It was pointed out that this should be reopened here since the issue lies with boccoli-babel-transpiler using @babel/polyfill which is deprecated
#176 https://github.com/ember-cli/ember-cli/issues/8952#issuecomment-562145348

---

Output from `npm ls -g core-js`

```
/../../.nvm/versions/node/v12.13.1/lib
└─┬ ember-cli@3.14.0
  └─┬ broccoli-babel-transpiler@7.3.0
    └─┬ @babel/polyfill@7.7.0
      └── core-js@2.6.1
```

**Comment by auvipy** [comment]
this is pretty old

**Comment by v1shaL-b** [comment]
> 
> 
> this is pretty old

i know it old... u have a solution for this?

**Comment by rwjblue** [comment]
Resolved in https://github.com/babel/broccoli-babel-transpiler/pull/191
