### ISSUE TITLE
Move babel specific options into `options.babel` property.

### ISSUE THREAD

**Issue by rwjblue** [babel/broccoli-babel-transpiler#189]
Currently we try to treat this packages `options` as **both** Broccoli specific options _**and**_ Babel's options. This is quite painful (passing another option to the Broccoli plugin is actually a breaking change for the babel transpilation side of things) and not terribly useful.

We should refactor our incoming options to move the babel specific options into `options.babel` so that we can delete the following munging of `options`:

https://github.com/babel/broccoli-babel-transpiler/blob/ff975c0f5eee552b1c7aa6bd33609969ae20625b/index.js#L60-L70

**Comment by nlfurniss** [comment]
I can take this on in a separate PR
