### ISSUE TITLE
@babel/polyfill 7.4.0+ has been deprecated

### ISSUE THREAD

**Issue by SergeAstapov** [babel/broccoli-babel-transpiler#197]
Per https://www.npmjs.com/package/@babel/polyfill:

> This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.

This is similar to https://github.com/babel/ember-cli-babel/issues/298

**Comment by rwjblue** [comment]
This option was removed in https://github.com/babel/broccoli-babel-transpiler/pull/191
