### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by francoislaberge** [babel/broccoli-babel-transpiler#23]
hey,

I've been having a hard time getting a workflow for getting my code to incrementally transpile from es6 to es5. I can get gulp or grunt to work but not very cleanly, I can't find any example projects that work as is. 

For example on this homepage you have this example code:
```
var esTranspiler = require('broccoli-babel-transpiler');
var scriptTree = esTranspiler(inputTree, options);
```

What does inputTree have to be? I'm finding broccoli documentation in general obtuse or when not to be geared more towards front end devs. I'm building a purely atom-shell (now electron) app.

Could someone point me to an example app that does takes a ```src``` folder and transpiles it using this module to a ```lib``` folder. Ideally with it rebuilding things as I change them. I assume that's how ```broccoli serve``` is supposed to work. 

Any help would be appreciated,
Francois

**Comment by givanse** [comment]
I'm working on such examples, keep an eye on: https://github.com/givanse/broccoli-babel-examples

**Comment by stefanpenner** [comment]
@givanse feel free to submit a PR with a link to those from the readme.
