### ISSUE TITLE
sourceMap idea

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#3]
the YPT guys @caridy and @ericf may want to chime in.

i believe the two approaches are likely:

* by convention expect a sibling .map file: https://github.com/mmun/broccoli-es6-module-transpiler/commit/72985d14b51ac37a15fe794d475ea44817f63b54
* generate inline source maps

I like the last one the best, as it prevents the dual file path.

Would love to hear your thoughts.

**Comment by caridy** [comment]
Just to clarify on the input, analyze the source, if the source has the sourcemap directive (inline or relative), consume it, and generate the new inline map by default, with an optional configuration to generate a sibling, in case this transformation is the last one, although we plan to provide a compelling tool to extract an inline sourcemap into a .map (maybe that already exists out there).

**Comment by myfreeweb** [comment]
Yes, [it exists, I made a broccoli plugin for it](https://github.com/myfreeweb/broccoli-source-map).  All broccoli plugins should take inline source maps as input and produce them as output.  Then the user should stick a `sourceMap.extract()` at the end of the pipeline. Problem solved.

**Comment by stefanpenner** [comment]
this seems to have gone stale.
