### ISSUE TITLE
Virus threat detected in one of babel-core files

### ISSUE THREAD

**Issue by xamoom-pali** [babel/broccoli-babel-transpiler#47]
Hi,

I am running an ubuntu machine with COMODO Antivirus installed. I have working on a project written in EmberJS using ember-cli and facing an issue: the antivirus program has detected 2 threats in following files:
EMBER_PROJECT/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/core-js/modules/core.log.js

EMBER_PROJECT/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/core-js/library/modules/core.log.js

Further description I am getting is: "Heur.Dual.Extensions"

Any idea what is going on here?
Thanks in advance
Pavol

**Comment by stefanpenner** [comment]
sounds like COMODO Antivirus is triggering on a false positive.

the error log also indicates which [project](https://github.com/zloirock/core-js) the issue should likely be opened on:
```
.../core-js/modules/core.log.js
      ^
```
