### ISSUE TITLE
save usedHelpers meta

### ISSUE THREAD

**Issue by krisselden** [babel/broccoli-babel-transpiler#50]
Save the babel meta to a json file so that a babel helpers module can be compiled later.  Maybe even add an import babelHelpers from 'babel-helpers';  in a source map friendly way so that a helpers module can be built when the app is packaged.

**Comment by stefanpenner** [comment]
i think the plan is to tree-shake prebuilt, but you recommend aggregating and compiling the helpers after the fact?

May be a good interim step.

**Comment by krisselden** [comment]
For reference `require("babel").transform("code").metadata.usedHelpers;`

**Comment by krisselden** [comment]
And `require("babel").buildExternalHelpers(usedHelpers)`

**Comment by stefanpenner** [comment]
Will gladly accept a PR if this is still applicable.
