### ISSUE TITLE
persistent-cache + exportModuleMetadata are not compatible

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#53]
- [ ] make it work
- [ ] re-enable persist when exportModuleMetadata is enabled

cc @chadhietala (also note, exportModuleMetadata relies on private API _cache ...)

**Comment by chadhietala** [comment]
Why does this not work?

**Comment by krisselden** [comment]
would it not be better to save the metadata the async cache?

**Comment by rwjblue** [comment]
@krisselden - Yes, that is what my suggestion is. 😺

**Comment by stefanpenner** [comment]
I think this is no longer a thing
