### ISSUE TITLE
browserPolyfill option does not work

### ISSUE THREAD

**Issue by anshulguleria** [babel/broccoli-babel-transpiler#59]
I was trying the option `browserPolyfill` option but it does not work but when i write my own logic in my `Brocfile.js` to merge the `browser-polyfill.js` file it works as expected.

Picked the logic to copy file from here: https://hacks.mozilla.org/2015/06/es6-in-depth-babel-and-broccoli/

code:

``` js
babelCorePath = require.resolve('broccoli-babel-transpiler');

babelCorePath = babelCorePath.replace('index.js', 'node_modules/babel-core/');

var projFiles = babel('src', {
    filterExtensions: [ 'es6'],
    browserPolyfill: true
});

var babelCoreTree = funnel(babelCorePath, {
    files: ['browser-polyfill.js']
});

projFiles = mergeTrees([projFiles, babelCoreTree]);

```

**Comment by givanse** [comment]
I'm guessing you were using the latest version `5.4.5`, right? Did you get this in the console?

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

**Comment by givanse** [comment]
The article is a little *outdated* now, if you still want to add the polyfill by yourself, see: https://github.com/babel/broccoli-babel-transpiler/blob/master/index.js#L51 (its very similar)

**Comment by anshulguleria** [comment]
@givanse Yeah you are right I was using `5.4.5` and thats exactly the error I got in console. But does that mean 5.4.5 does not support `browserPolyfill` property?

**Comment by givanse** [comment]
It means we have a bug.

**Comment by givanse** [comment]
@chadhietala Why was the change from `cauliflower-filter` to `broccoli-filter` necessary?

**Comment by chadhietala** [comment]
This project currently uses `broccoli-persistent-filter`, which consolidated the ideas. It's still a fork and eventually will be in `broccoli-filter`.

**Comment by stefanpenner** [comment]
I believe this has been addressed
