### ISSUE TITLE
Babel options "only" and "ignore" are not respected

### ISSUE THREAD

**Issue by smfoote** [babel/broccoli-babel-transpiler#61]
Babel accepts an array of glob or regex of paths for `only`, but those options do not appear to be respected when passed to the plugin.

**Comment by jimmyhchan** [comment]
related? https://phabricator.babeljs.io/T6726

**Comment by eventualbuddha** [comment]
This appears to be fixed with [babel v6.14.0](https://github.com/babel/babel/releases/tag/v6.14.0).

**Comment by Turbo87** [comment]
thanks @eventualbuddha, closing this issue for now.
