### ISSUE TITLE
fix dep-graph.json and with tree-diffing

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#63]

**Comment by stefanpenner** [comment]
@chadhietala may interest you (as we get start with reviving package/linker stuff)

**Comment by chadhietala** [comment]
@stefanpenner Is the issue that output is N + 1?

**Comment by stefanpenner** [comment]
two issues:

- [ ] n+1 output (we can fix this in broccoli-persistent-filter, but adding better hooks for this)
- [ ] there is no _cache naymore
