### ISSUE TITLE
fix windows test

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#65]
just line-ending differences in output matching

cc @kellyselden got cycles ?

**Comment by kellyselden** [comment]
I will hit up tonight

**Comment by stefanpenner** [comment]
thank you kindly good sir.

**Comment by kellyselden** [comment]
don't thank me yet...

**Comment by stefanpenner** [comment]
:tractor:

**Comment by kellyselden** [comment]
duplicate #54
