### ISSUE TITLE
cache not documented (or disable-able)?

### ISSUE THREAD

**Issue by shaunc** [babel/broccoli-babel-transpiler#68]
I was having an issue with `imports` in index.js

https://github.com/givanse/broccoli-babel-examples/issues/4

and found that `resolveModuleSource` wasn't being called. When I upgraded this package from 5.4.5 to 5.5.0, I found that `resolveModuleSource` was called... once. However, before I could do any debugging it stopped working again. Incidentally, I fiddled with another option and got `resolveModuleSource` to run again. I am guessing that it is caching values in global location (hmm... perhaps ~/.babel.json?) 

However, this isn't documented anywhere I can find, nor can I find out how to turn off global cache so I can debug  `resolveModuleSource`. Probably I will be able to continue flipping irrelevant switches to invalidate cache and debug enough to fix my problem, but this seems a suboptimal solution.

**Comment by ivanvanderbyl** [comment]
It appears you can set `persist: false,` in options to disable the transpiler options caching. Only loosely tested this, but let me know if it works. I'm on `5.5.0`

**Comment by shaunc** [comment]
persist: false seems to work -- thanks!
