### ISSUE TITLE
Importing relative modules

### ISSUE THREAD

**Issue by nicoecheza** [babel/broccoli-babel-transpiler#77]
Hi,
I currently have a simple setup to transpile multiple files into a single file inside a folder (pretty common :dancer: ). Everything works well, except when I try to import a file into another one, and the compiled file get's messed up since it is still referencing to the relative path instead of having it imported and transpiled.

Someone knows a way to fix this? 
Thanks!

**Comment by Turbo87** [comment]
@nicoecheza can you provide an example repo that demonstrates your issue?
