### ISSUE TITLE
This project appears to introduce ~4864 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#90]
own files we may not want:
- expectations  7
- fixtures 6

deps we may want to investigate
- node_modules 4842
- [ ] babel-core 3257
- [x] broccoli-funnel 581
- [ ] broccoli-persistent-filter 965 https://github.com/stefanpenner/broccoli-persistent-filter/issues/70
- [ ] clone 8
- [ ] json-stable-stringify 30

**Comment by locks** [comment]
https://github.com/broccolijs/broccoli-funnel/pull/74

**Comment by locks** [comment]
https://github.com/babel/broccoli-babel-transpiler/pull/91

**Comment by locks** [comment]
https://github.com/babel/babel/pull/3634

**Comment by locks** [comment]
https://github.com/substack/json-stable-stringify/pull/22/files
